更新免费代理每天

diff --git a/.github/workflows/clone.yml b/.github/workflows/clone.yml
--- a/.github/workflows/clone.yml
+++ b/.github/workflows/clone.yml
@@ -17,6 +17,39 @@ jobs:
         steps:
             - name: Checkout code
               uses: actions/checkout@v2
+            - name: 设置环境 Python 3.8
+              uses: actions/setup-python@v2
+              with:
+                python-version: "3.8"
+            - name: 安装依赖
+              run: |
+                  python -m pip install --upgrade pip
+                  pip install requests lxml
+            - name: 下载文件
+              run: |
+               python -c '
+                import requests
+                from lxml import html
+                
+                url = "https://jc.guanxi.cloudns.be/"
+                try:
+                    response = requests.get(url, timeout=10)
+                    response.raise_for_status()  
+                    tree = html.fromstring(response.text)
+                    a_tag = tree.xpath("//div[@class='header']/a")[0]
+                    link = a_tag.get("href")
+                    
+                    local_filename = "guanxi"
+                    with requests.get(link, stream=True, timeout=10) as r:
+                        r.raise_for_status()
+                        with open(local_filename, "wb") as f:
+                            for chunk in r.iter_content(chunk_size=8192):
+                                if chunk:
+                                    f.write(chunk)
+                    print(f"File downloaded successfully to {local_filename}")
+                except Exception as e:
+                    print(f"An error occurred: {e}")
+                '
             - name: 创建版本号
               run: |
                  if ! curl -L --silent --output ./version.sh ${{ env.VERSION}}; then
@@ -36,7 +69,9 @@ jobs:
                 if [ ! -d "./bak" ]; then
                     mkdir -p ./bak
                 fi
-
+                if [ ! -d "./proxy" ]; then
+                    mkdir -p ./proxy
+                fi
                 # 备份原始文件
                 if [ -f "./filter_remote/Reject.list" ]; then
                     mv ./filter_remote/Reject.list ./bak/Reject.list.bak
@@ -47,14 +82,17 @@ jobs:
                     echo "Failed to move the file."
                     exit 1
                 fi
-
+                if ! mv ./guanxi ./proxy/guanxi; then
+                    echo "Failed to move the file."
+                    exit 1
+                fi
                 echo "File successfully downloaded, backed up, and moved."
             - name: 更新
               run: |
                 git config --local user.email ${{ secrets.EMAIL }}
                 git config --local user.name ${{ secrets.NAME }}
                 git pull
-                git add bak filter_remote version
+                git add bak filter_remote version proxy
                 git commit -m "Update"
                 git push
                 
