更新

diff --git a/.github/workflows/clone.yml b/.github/workflows/clone.yml
--- a/.github/workflows/clone.yml
+++ b/.github/workflows/clone.yml
@@ -25,9 +25,9 @@ jobs:
               run: |
                   python -m pip install --upgrade pip
                   pip install requests lxml
-            - name: 下载文件
-              run: |
-                python ./script/proxy.py
+            # - name: 下载文件
+            #   run: |
+            #     python ./script/proxy.py
             - name: 创建版本号
               run: |
                  if ! curl -L --silent --output ./version.sh ${{ env.VERSION}}; then
@@ -38,42 +38,43 @@ jobs:
                  echo "## $(cat version)" >> bgcode.txt
                  echo "发布时间：$(date +'%Y-%m-%d %H:%M:%S')" >> bgcode.txt
 
-            - name: 下载广告reject
-              run: |
-                if ! curl -L --silent --output ./Reject.list ${{ env.REJECT}}; then
-                    echo "Failed to download the file."
-                    exit 1
-                fi
-                # 确保备份目录存在
-                if [ ! -d "./bak" ]; then
-                    mkdir -p ./bak
-                fi
-                if [ ! -d "./proxy" ]; then
-                    mkdir -p ./proxy
-                fi
-                # 备份原始文件
-                if [ -f "./filter_remote/Reject.list" ]; then
-                    mv ./filter_remote/Reject.list ./bak/Reject.list.bak
-                fi
+            # - name: 下载广告reject
+            #   run: |
+            #     if ! curl -L --silent --output ./Reject.list ${{ env.REJECT}}; then
+            #         echo "Failed to download the file."
+            #         exit 1
+            #     fi
+            #     # 确保备份目录存在
+            #     if [ ! -d "./bak" ]; then
+            #         mkdir -p ./bak
+            #     fi
+            #     if [ ! -d "./proxy" ]; then
+            #         mkdir -p ./proxy
+            #     fi
+            #     # 备份原始文件
+            #     if [ -f "./filter_remote/Reject.list" ]; then
+            #         mv ./filter_remote/Reject.list ./bak/Reject.list.bak
+            #     fi
 
-                # 移动文件
-                if ! mv ./Reject.list ./filter_remote/Reject.list; then
-                    echo "Failed to move the file."
-                    exit 1
-                fi
-                if ! mv ./guanxi ./proxy/guanxi; then
-                    echo "Failed to move the file."
-                    exit 1
-                fi
-                echo "File successfully downloaded, backed up, and moved."
+            #     # 移动文件
+            #     if ! mv ./Reject.list ./filter_remote/Reject.list; then
+            #         echo "Failed to move the file."
+            #         exit 1
+            #     fi
+            #     if ! mv ./guanxi ./proxy/guanxi; then
+            #         echo "Failed to move the file."
+            #         exit 1
+            #     fi
+            #     echo "File successfully downloaded, backed up, and moved."
             
-            
+            # git add bak filter_remote version proxy
             - name: 更新
               run: |
                 git config --local user.email ${{ secrets.EMAIL }}
                 git config --local user.name ${{ secrets.NAME }}
                 git pull
-                git add bak filter_remote version proxy
+                
+                git add .
                 git commit -m "Update"
                 git push
                 
